name: "Daily deploy snapshot"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'


jobs:
  release:
    runs-on: ubuntu-latest
    name: release

    steps:
      - uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Maven release 999-SNAPSHOT
        run: |
          git checkout -b release
          mvn -B release:prepare -Prelease,framework,examples -DautoVersionSubmodules -DreleaseVersion=999-SNAPSHOT
          mvn -B release:perform -DskipITs -Prelease,framework
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
